### PR TITLE
bottom navigation added

### PR DESCRIPTION
**Pull request by sakshiisaxena**
Bottom navigation bar added #10 

Screenshot_1624534049

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Make the bottommost line as `Made with ♥ in  India`

**Comment by sakshiisaxena** [comment]
> Make the bottommost line as `Made with ♥ in India`

updated with required changes @smaranjitghose

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Convert level to uppercase cause it will give a warning if u don't.

Secondly ther's a weird motion of icons on clicking try resolving it. Below is the clip

https://user-images.githubusercontent.com/40017559/123298798-7f8f9a80-d536-11eb-8eab-56c79a567fdf.mp4

**Comment by sakshiisaxena** [comment]
> Convert level to uppercase cause it will give a warning if u don't.
> 
> Secondly ther's a weird motion of icons on clicking try resolving it. Below is the clip
> 
>  SVID_20210624_215049_1.mp4


fixed the requested changes @anushbhatia

**Review by Procoder16 — CHANGES_REQUESTED** [review]
You can still modify the bottom navigation bar, for example, when a particular tab is selected, it should look as if it is selected somehow either by highlighting the icon or switch between filled or unfilled icons.

**Comment by sakshiisaxena** [comment]
> You can still modify the bottom navigation bar, for example, when a particular tab is selected, it should look as if it is selected somehow either by highlighting the icon or switch between filled or unfilled icons.

Highlighted the icons and the labels when tapped.

**Review by Procoder16 — APPROVED** [review]
Good Job!!
Let's wait for the PA's approval.

**Comment by anushbhatia** [comment]
@sakshiisaxena great work. Just a minor change take a git pull and remove  .flutterplugins .flutterpuligin dependencies. 
Also, take` git pull` once before pushing so u will be able to see the latest changes and there won't be a merge conflict.

**Comment by sakshiisaxena** [comment]
> @sakshiisaxena great work. Just a minor change take a git pull and remove .flutterplugins .flutterpuligin dependencies.
> Also, take` git pull` once before pushing so u will be able to see the latest changes and there won't be a merge conflict.

updated.

**Pull request merged**
