### PR TITLE
Exit bpm process

### PR DESCRIPTION
**Pull request by Priyanshu078**
Now the BPM estimating process stops when the app is in the background.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
It shows a lot of errors on the home page can you see what's the reason.

**Comment by Priyanshu078** [comment]
@anushbhatia  Exit BPM process and Adding Timer issue code was merged when you merged the adding Timer pull request.
So I think now no need for this pull request because both the issues code was merged with the pull request of Timer.

**Comment by anushbhatia** [comment]
before the timer issue, this error was showing up. There was no error in that PR it shows errors here only.

**Comment by anushbhatia** [comment]
create a new PR with this same code now it is working

**Pull request closed without merging**
