### PR TITLE
Fixed Issue #4

### PR DESCRIPTION
**Pull request by dibyanshu-mohanty**
Added Illustration
Screenshot_1624592752

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Resolve the overflow error by reducing sizedbox

**Comment by dibyanshu-mohanty** [comment]
Requested changes made

**Comment by dibyanshu-mohanty** [comment]
Requested changes made

**Comment by dibyanshu-mohanty** [comment]
Requested changes completed
Screenshot_1624627852

**Review by Procoder16 — APPROVED** [review]
Overflowed pixel resolved. Good job!!!
Let's wait for the PA's approval.

**Comment by anushbhatia** [comment]
one minor change just move the image present in the` images` folder to `assets` and delete images. SO there will be only import images line.
And In pubspec.yaml keep only the assets folder.
Awesome Work @dibyanshu-mohanty

**Pull request closed without merging**
