### PR TITLE
Fixing #9 : Added dark Mode 

### LINKED ISSUE #9: Adding Dark Mode
Currently, we don't have a dark mode for that app.
For references and colour codes you can refer this https://github.com/smaranjitghose/DocLense
Either add the button in the navigation bar or create that in-app bar.

### PR DESCRIPTION
**Pull request by noman2002**
Fixes #9 
Added dark mode.
Theme Mode is changed to themeMode.system
Will add toggle button for switching between dark mode and light mode soon.

### CODE REVIEW

**Review by Procoder16 — CHANGES_REQUESTED** [review]
I would like to see some changes to the modifications you have made:
1. The combination of grey isn't looking that attractive. Instead, if you use a combination of dark blue colors, it would look better. So use a combination of 0xFF0B1328 and 0xFF1D2740.
2. The second thing is the icons in the bottom navigation bar. When the icon is inactive, it is set to black which should have been set to white instead.
3. And do add that toggle button because then only the changes can be merged with the main branch.

**Comment by noman2002** [comment]
Should I also have to change the button color?

**Comment by Procoder16** [comment]
> Should I also have to change the button color?

Yeah you can use 0xFF3172F5 for the buttons.

And, the colors that I have mentioned earlier, use the lighter one for the appBar and the darker one for the rest.

**Comment by noman2002** [comment]
I have made the required changes. Please review it

**Review by Procoder16 — APPROVED** [review]
Perfectly executed the way I wanted. Good Job!!!
Now let's wait for the PA's approval. 
Well done.

**Comment by smaranjitghose** [comment]
@noman2002 Kindly let us know which program are you a part of so that we can provide the appropriate labels to the PR

**Comment by noman2002** [comment]
@smaranjitghose Please provide the tags for LGMSOC. I'm part of lgmsoc program.

**Pull request merged**
