### PR TITLE
Fixed Issue #4

### PR DESCRIPTION
**Pull request by dibyanshu-mohanty**
Added Illustration below Buttons.
Screenshot_1623907106

### CODE REVIEW

**Comment by Procoder16** [comment]
@dibyanshu-mohanty  The addition of the illustration is ok but I think you should have updated the project before making the PR as the project was already updated with the rounded buttons. Apart from that, rest everything is fine, and let's wait for the response from PA.

**Comment by dibyanshu-mohanty** [comment]
The PR wasn't merged at the time I worked with the project , if the PA wants then I can do it with the updated project

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Avoid .idea files and add them in gitignore so that they won't come in the PR. also resolve the merge conflict.

**Comment by anushbhatia** [comment]
Any update?

**Comment by dibyanshu-mohanty** [comment]
Yep , Will Do the PR by tonight

**Pull request closed without merging**
