### PR TITLE
PR for the issue Timer Enhancement

### LINKED ISSUE #22: Timer Enhancement
To add a visual effect of the timer a circular progress bar. So that user can know how much time is left.
[Some Refrence](https://medium.com/flutterdevs/creating-a-countdown-timer-using-animation-in-flutter-2d56d4f3f5f1)

### PR DESCRIPTION
**Pull request by SanjayDevTech**
closes #22 

- Added Timer with circular progress bar
- Rounded curve
- Customisable widget

Screenshot_20210628-214755

### CODE REVIEW

**Review by Procoder16 — CHANGES_REQUESTED** [review]
the circular progress bar looks good but it would be better if you can change the colour combination of the circular progress bar from black/red to something according to the current theme

**Comment by SanjayDevTech** [comment]
@Procoder16 Sure I'll change that

**Comment by SanjayDevTech** [comment]
@Procoder16 
- Changed color from Black - Red to LightBlue - Blue

Screenshot_20210629-082953

**Review by Procoder16 — APPROVED** [review]
Good Job!!!
The changes to this issue now look nice to me.
Let's wait for the PA if they want anything else.

**Comment by SanjayDevTech** [comment]
😄 Thanks

**Review by smaranjitghose — APPROVED** [review]

**Pull request merged**
